list:
    @just --list

# TODO: Make these both work without relying on pip!
beepy-install:
    @python -m pip install {{ cookiecutter.project_slug }}

beepy-remove:
    @python -m pip uninstall {{ cookiecutter.project_slug }}

run:
    @poetry run {{ cookiecutter.project_slug }}

# Run the tests
test:
    @poetry run pytest tests

# Initialize the application
init:
    poetry install
    echo "Application initialized successfully."
    poetry run pre-commit install
    echo "Pre-commit hooks set up."
